version: '2'

services:
  pw-tests:
    container_name: 'my-test'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CI=true
      - HTTP_CREDENTIALS_USERNAME=guest
      - HTTP_CREDENTIALS_PASSWORD=welcome2qauto
      - BASE_URL=https://qauto.forstudy.space