name: 'Playwright test'

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: string
        default: Run tests

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      env:
        ENV: dev
        HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
        HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: npm run test 
    
    - name: Upload report to artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ci-report
        path: playwright-report/
        retention-days: 3
